[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "wrepy"
version = "0.0.1"
dependencies = [
  "frozendict",
  "more_itertools",
  "rich",
  "tqdm",
  "numpy",
  "scipy",
  "more_itertools",
]
requires-python = ">=3.10"
